POST http://localhost:3001/api/todos/
Content-Type: application/json

{
    "content": "Do the Laundry"

}

###
POST http://localhost:3001/api/todos/reset

###
PUT http://localhost:3001/api/todos/6270f316eecd4443de5f09de
Content-Type: application/json

{
    "status": false
}