POST http://localhost:3001/api/todos/
Content-Type: application/json

{
    "content": "Do the Laundry"

}

###
POST http://localhost:3001/api/todos/reset

###
DELETE http://localhost:3001/api/todos/6290a04cbfd8835c28d356d6



###
GET http://localhost:3001/api/todos/
# Content-Type: application/json

# {
#     "status": false
# }